### ISSUE TITLE
Error running Isopret CLI for interpro domain analysis

### ISSUE THREAD

**Issue by karleg** [TheJacksonLaboratory/isopretGO#170]
I am trying to run the CLI for the last frame of the new figure that shows different DAS/DGE counts over the 100 datasets.  This frame counts he occurrence of interpro domains.  I get the following error:

21:19:52.858 INFO  d.c.c.j.data.JannovarDataSerializer - Deserializing JannovarData from /Users/karleg/data/hg38_ensembl.ser
21:20:00.816 INFO  d.c.c.j.data.JannovarDataSerializer - Deserialization took 7.95 sec.
21:20:01.219 INFO  o.j.i.c.impl.jannovar.JannovarReader - Parsed geneToTranscriptListMap with 34912 entries
21:20:01.226 INFO  o.j.i.c.impl.DefaultIsopretProvider - Loaded JannovarReader with 34912 symbols
21:20:01.626 INFO  o.j.i.c.impl.DefaultIsopretProvider - Loaded HGNC Map with 26710 symbols
21:20:01.881 INFO  o.j.i.c.i.r.RnaSeqResultsParser - Could not find symbols for 597 accessions.
java.lang.NullPointerException: Cannot invoke "org.monarchinitiative.phenol.ontology.data.Ontology.containsTerm(org.monarchinitiative.phenol.ontology.data.TermId)" because "ontology" is null
	at org.jax.isopret.core.impl.go.TranscriptFunctionFileParser.parseFunctionFile(TranscriptFunctionFileParser.java:56)
	at org.jax.isopret.core.impl.go.TranscriptFunctionFileParser.<init>(TranscriptFunctionFileParser.java:79)
	at org.jax.isopret.core.impl.DefaultIsopretProvider.initFromTranscriptFunctionParser(DefaultIsopretProvider.java:158)
	at org.jax.isopret.core.impl.DefaultIsopretProvider.transcriptIdToGoTermsMap(DefaultIsopretProvider.java:95)
	at org.jax.isopret.core.impl.DefaultIsopretProvider.initContainers(DefaultIsopretProvider.java:138)
	at org.jax.isopret.core.impl.DefaultIsopretProvider.transcriptContainer(DefaultIsopretProvider.java:123)
	at org.jax.isopret.cli.command.InterproOverrepCommand.call(InterproOverrepCommand.java:47)
	at org.jax.isopret.cli.command.InterproOverrepCommand.call(InterproOverrepCommand.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jax.isopret.cli.Main.main(Main.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

Could you please let me know how to resolve this?

**Comment by pnrobinson** [comment]
This issue was this in DefaultIsopretProvider (in the isopret-core module, in the impl package.
This:

```
 IsopretContainerFactory isoContainerFac = new IsopretContainerFactory(geneOntology,
                transcriptIdToGoTermsMap(), gene2GoMap());
```
needs to be this (i.e., add parentheses to geneOntology)
```
 IsopretContainerFactory isoContainerFac = new IsopretContainerFactory(geneOntology(),
                transcriptIdToGoTermsMap(), gene2GoMap());
```

**Comment by pnrobinson** [comment]
@karleg  I am not able to log into GitHub right now because I cannot get into my JAX laptop. If you make the above change, everything should work.

**Comment by karleg** [comment]
this change resolved the problem

**Comment by pnrobinson** [comment]
Let's lkeave this open until the source code can be fixed

**Comment by karleg** [comment]
The fix that you suggested is in the source code - do you mean that you have a copy of this repository in another location?

**Comment by pnrobinson** [comment]
also fixing in develop branch,
